version: "3"
services:
  github_copilot_test:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: github_copilot_test-image
    container_name: github_copilot_test-container
    tty: true
